use async_channel::Sender;
// This code was autogenerated with `dbus-codegen-rust --file test.xml`, see https://github.com/diwic/dbus-rs
use dbus::{self as dbus, blocking::{Connection, stdintf::org_freedesktop_dbus::PropertiesPropertiesChanged}};
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;
use futures::executor::block_on;
use crate::message::Message;
use std::sync::{Mutex, OnceLock};

pub fn cancel_battery_check() -> &'static Mutex<bool> {
    static INSTANCE: OnceLock<Mutex<bool>> = OnceLock::new();
    INSTANCE.get_or_init(|| Mutex::new(false))
}

fn last_address() -> &'static Mutex<String> {
    static INSTANCE: OnceLock<Mutex<String>> = OnceLock::new();
    INSTANCE.get_or_init(|| Mutex::new(String::new()))
}

fn device_path() -> &'static Mutex<String> {
    static INSTANCE: OnceLock<Mutex<String>> = OnceLock::new();
    INSTANCE.get_or_init(|| Mutex::new(String::new()))
}

pub trait OrgBluezBattery1 {
    fn percentage(&self) -> Result<u8, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: std::ops::Deref<Target=T>> OrgBluezBattery1 for blocking::Proxy<'a, C> {
    fn percentage(&self) -> Result<u8, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.bluez.Battery1", "Percentage")
    }
}

// if battery state changes, then update the UI
fn handle_properties_updated(sender: Sender<Message>) {
    let conn = Connection::new_system().unwrap();
    let path = device_path().lock().unwrap().clone();
    let proxy = conn.with_proxy("org.bluez", &path, std::time::Duration::from_millis(5000));
    
    let reported = if let Ok(val) = proxy.percentage() {
        val as i8
    }
    else {
        -1
    };
    block_on(sender.send(Message::UpdateBatteryLevel(reported))).expect("cannot send message");
}

/// Gets (and continues getting) the battery level of a device until it is canceled
pub fn get_battery_for_device(address: String, adapter: String, sender: Sender<Message>) {
    if *last_address().lock().unwrap() == address {
        println!("stopped checking battery, last addressed matched");
        return;
    } else {
        *last_address().lock().unwrap() = address.clone();
    }

	// to get the path to this device make it so the full path is 
	// something like "/org/bluez/dev_XX_XX_XX_XX_XX_XX"
	let fixed_address = "dev_".to_string() + &address.replace(':', "_");
	let path = "/org/bluez/".to_string() + &adapter + "/" + &fixed_address;
	*device_path().lock().unwrap() = path.clone();
	// println!("full path to device is: {}", path);

	let conn = Connection::new_system().unwrap();
    let proxy = conn.with_proxy("org.bluez", path, std::time::Duration::from_millis(5000));

    let sender_clone = sender.clone();
    proxy.match_signal(move |_: PropertiesPropertiesChanged, _: &Connection, _: &dbus::Message| {
        let clone = sender_clone.clone();
	    handle_properties_updated(clone);
	    true
    }).expect("can't match signal");

    // send a first reported battery to the UI as we don't want to wait for the battery to change to let the user know what it is
    // as that could take an unreasonably long time with the dbus implementation
    // should add a fallback (or maybe make this the fallback) with a better get battery method
    let first_reported = if let Ok(val) = proxy.percentage() {
        val as i8
    }
    else {
        -1
    };
    
    block_on(sender.send(Message::UpdateBatteryLevel(first_reported))).expect("cannot send message");
    
    // get battery till canceled
    loop {
        conn.process(std::time::Duration::from_millis(1000)).expect("cannot process battery check request");
        if *cancel_battery_check().lock().unwrap() && address != *last_address().lock().unwrap() {
            println!("stopped checking battery");
            *cancel_battery_check().lock().unwrap() = false;
            break;
        }
    }
}
